apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-logs-reader
spec:
  selector:
    matchLabels:
      app: node-logs-reader
  template:
    metadata:
      labels:
        app: node-logs-reader
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool:latest
        command: ["/bin/sh", "-c"]
        args: ["tail -f /host/log/syslog"]
        volumeMounts:
        - name: host-log
          mountPath: /host/log
          readOnly: true
      volumes:
      - name: host-log
        hostPath:
          path: /var/log
          type: Directory
